import React, { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { toast } from 'react-toastify'
import Category, { CategoryData } from '../components/Category'
import { CardData } from '../components/Card'
import SubmitModal from '../components/SubmitModal'

export type SelectedCard = {
  [key: string]: CardData
}

const Home: NextPage = () => {
  const [categories, setCategories] = useState<CategoryData[]>([])
  const [selectedCards, setSelectedCards] = useState<SelectedCard>({})
  const [isOpen, setIsOpen] = useState(false)

  // get data from API and store to state
  useEffect(() => {
    const getCategoriesData = async () => {
      const response = await fetch('api/ballots', { method: 'GET' })
      const data = await response.json()
      if (data.items) setCategories(data.items)
    }
    getCategoriesData()
  }, [])

  // Update selected items
  const updateItems = (categoryId: string, card: CardData) => {
    const tempCards = { ...selectedCards }
    tempCards[categoryId] = card
    setSelectedCards({ ...tempCards })
  }

  // Handle submit items
  const submitItems = () => {
    // Include submit logic here
    console.log('Include submit logic here')
    if (!Object.keys(selectedCards).length) {
      toast.warn('No nominees selected!')
      return
    }
    setIsOpen(true)
    toast.success('Submitted successfuly!')
  }

  // handle modal close
  const handleModalClose = () => {
    setIsOpen(false)
  }

  return (
    <div className="min-h-screen py-0 px-4 bg-pg-bg">
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-roboto">
        <div className="py-10 mmd:py-20 max-w-7xl mx-auto relative">
          <h1 className=" text-3xl mmd:text-5xl uppercase font-bold text-center text-white mb-6 mmd:mb-10">
            Awards 2021
          </h1>
          {categories.map((categoryData) => (
            <Category
              categoryData={categoryData}
              key={categoryData.id}
              updateItems={updateItems}
            />
          ))}
          <button
            className="absolute bottom-5 right-0 text-white hover:text-black focus:text-black bg-card-selected-bg hover:bg-card-bg focus:bg-btn-focus-bg px-5 py-2 rounded transition-all"
            onClick={submitItems}
          >
            Submit ballot
          </button>
        </div>
      </main>
      {isOpen && (
        <SubmitModal
          isOpen={isOpen}
          selectedCards={selectedCards}
          handleModalClose={handleModalClose}
        />
      )}
    </div>
  )
}

export default Home
